application: oponger
version: 2
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: /images/favicon\.ico
- url: /js
  static_dir: js
- url: .*
  script: main.py
  login: required

builtins:
- remote_api: on

